#pragma once

/* Per-build XOR key -- regenerated by obfstr.py each build */
#ifndef _SKY
#define _SKY 0xac
#endif

static inline const char *_xds(const unsigned char *e, int n, char *d) {
    int i;
    for (i = 0; i < n; i++) d[i] = (char)((unsigned char)e[i] ^ (unsigned char)_SKY);
    d[n] = '\0';
    return d;
}

/* Decrypt n XOR-encrypted bytes onto the stack; lifetime tied to enclosing function */
#define _S(n, ...) _xds((const unsigned char[]){__VA_ARGS__}, (n), (char *)__builtin_alloca((n) + 1))
